name: oxoo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0-417.2.beta"

dependencies:
  flutter:
    sdk: flutter
  app_review: ^2.1.1+1
  #packages_info: ^0.0.1-dev.1
  built_value: ^8.1.1
  carousel_slider: ^4.2.1
  chewie: ^1.4.0
  country_code_picker: ^3.0.0
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  #credit_card_input_form: ^2.3.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.0
  firebase_auth_web: ^5.3.2
  equatable: ^2.0.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter_bloc: ^7.0.1
  flutter_downloader: ^1.6.1
  flutter_keyboard_visibility: ^5.0.2
  #flutter_mdns_plugin: ^0.0.3
  flutter_pagewise: ^2.0.1
  #flutter_playout: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.7
  flip_card: ^0.7.0
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.1+3
  #wakelock: ^0.6.2
  #in_app_purchase: ^0.4.0
  meta: ^1.3.0
  moor: ^4.4.1
  onesignal_flutter: ^3.0.0
  permission_handler: ^10.2.0
  pinput: ^1.2.0
  provider: ^6.0.3
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.3.0
  url_launcher: ^6.0.9
  video_player: ^2.0.0
  webview_flutter: ^2.0.9
  youtube_player_flutter: ^8.0.0
  #audioplayers:
  app_links: ^3.4.1
  audio_service: ^0.18.9
  cached_network_image: ^3.2.3
  logging: ^1.1.0
  just_audio: ^0.9.30
  rxdart: ^0.27.7
  sliding_up_panel: ^2.0.0+1
  share_plus: ^6.3.0
  material_design_icons_flutter:  ^6.0.7096
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  palette_generator: ^0.3.3+2
  dart_des: ^1.0.2
  audiotagger: ^2.2.1
  on_audio_query: ^2.8.0
  marquee: ^2.2.3
  package_info_plus: ^3.0.2
  youtube_explode_dart: ^1.12.3
  #flutter_gen: ^5.1.0+1
  font_awesome_flutter: ^10.0.0
  flutter_credit_card: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/android_launcher_icon.png"
  bloc_test: ^3.0.0

dependency_overrides: null
#analyzer: ^0.41.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash_image.jpg
    - assets/logo.png
    - assets/android_launcher_icon.png
    - assets/drawer_icon/
    - assets/images/
    - assets/bottom_nav/
    - assets/images/ic_button_apple.png
    - assets/cover.jpg
    - assets/album.png
    - assets/artist.png
    - assets/song.png
    - assets/bg.png
    - assets/card_bg.png
